export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userSignUpConstants = {
  USER_SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}
export const getCategoryConstants = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',

  UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

  DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
}
export const productConstants = {
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',

  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

  DELETE_PRODUCT_BY_ID_REQUEST: 'DELETE_PRODUCT_BY_ID_REQUEST',
  DELETE_PRODUCT_BY_ID_SUCCESS: 'DELETE_PRODUCT_BY_ID_SUCCESS',
  DELETE_PRODUCT_BY_ID_FAILURE: 'DELETE_PRODUCT_BY_ID_FAILURE'
}

export const initialDataConstant = {
  GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
  GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
  GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}
export const pageTypeConstants = {
  CREATE_PAGE_TYPE_REQUEST: 'CREATE_PAGE_TYPE_REQUEST',
  CREATE_PAGE_TYPE_SUCCESS: 'CREATE_PAGE_TYPE_SUCCESS',
  CREATE_PAGE_TYPE_FAILURE: 'CREATE_PAGE_TYPE_FAILURE'
}
export const orderConstant = {
  GET_CUSTOMER_ORDER_REQUEST: 'GET_CUSTOMER_ORDER_REQUEST',
  GET_CUSTOMER_ORDER_SUCCESS: 'GET_CUSTOMER_ORDER_SUCCESS',
  GET_CUSTOMER_ORDER_FAILURE: 'GET_CUSTOMER_ORDER_FAILURE',

  UPDATE_CUSTOMER_ORDER_REQUEST: 'UPDATE_CUSTOMER_ORDER_REQUEST',
  UPDATE_CUSTOMER_ORDER_SUCCESS: 'UPDATE_CUSTOMER_ORDER_SUCCESS',
  UPDATE_CUSTOMER_ORDER_FAILURE: 'UPDATE_CUSTOMER_ORDER_FAILURE'
}
